version: '2'
services:
  web:
    build: .              # 使用当前文件夹下的　Dockerfile 构建
    ports:
     - "5000:5000"
  redis:
    image: "redis:alpine" # 直接使用镜像构建 redis
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - .:/bitnami/mariadb
    command: echo "hello world"