FROM ubuntu
MAINTAINER link "1162097842@qq.com" # 写入作者信息
ENV CREATED_AT 2020-12-25           # 设置环境变量
RUN apt-get update && \
apt-get install -y net-tools && \
apt-get install -y iputils-ping && \
apt-get install -y iproute2 && \
apt-get install -y libterm-readkey-perl

