apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness # Pod 名称
  labels: # 加上标签
    create_method: manual
    env: dev
spec:
  containers:
  - image: codekissyoung/kubia # 创建 Pod 使用的镜像
    name: kubia                # 容器名称
    # 假如探针检测失败，会重启该 Pod.　PS: 一次失败，将会再尝试检测几次
    livenessProbe:             # http 存活探针检测
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 15 # 延迟探测时间
    ports:
    - containerPort: 8080 # 应用监听的端口
      protocol: TCP
