apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-rc # Pod 名称
spec:
  replicas: 2 # 副本个数
  selector:   # 标签选择器
    app: kubia-rc
  template:
    metadata:
      labels:
        app: kubia-rc
    spec:
      containers:
        - name : kubia
          image: codekissyoung/kubia
          ports:
            - containerPort: 8080
