apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-label
  labels:
    create_method: manual
    env: dev
spec:
  containers:
  - image: codekissyoung/kubia
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP

