apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-rc-example # Pod 名称
spec:
  replicas: 2     # 副本个数
  selector:       # 标签选择器
    app: kubia-rc # RC 确保符合本标签的 Pod 的个数只有 2 个
  template:
    metadata:
      labels:
        app: kubia-rc
    spec:
      containers:
        - name : kubia
          image: codekissyoung/kubia
          ports:
            - containerPort: 8080
